[package]
name = "sniff"
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
edition = "2018"

[[bin]]
name = "sniffer"
path = "sniffer/main.rs"

[lib]
name = "iee_800_11"
path = "iee_800_11/lib.rs"

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.2"
log = "0.4"
simplelog = { version = "0.9", default-features = false }

bytes = "0.4"
byteorder = "1"
pcap = { version = "0.8", features = ['capture-stream'] }
radiotap = "1.3"
