[package]
name = "Wifitify"
description = "Monitor your wifi devices and create hook based behavior."
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
keywords = ["wifi", "montior", "hooks", "events"]
edition = "2018"

[dependencies]
# Error handling
anyhow = "1"
better-panic = "0.2"

# Async runtime
async-std = { version = "1", features = ['attributes'] }

# Cli
log = "0.4"
clap = "3.0.0-beta.2"
simplelog = { version = "0.9", default-features = false }

# Wifi related
libwifi = { path = "../../libraries/libwifi" }
pcap = { version = "0.8", features = ['capture-stream'] }
radiotap = "1.3"

# Database
chrono = "0.4"
sqlx = { version = "0.5", features = [ "runtime-async-std-rustls", "postgres", "chrono", "migrate" ] }
