[package]
name = "sniff"
version = "0.1.0"
authors = ["Arne Beer <contact@arne.beer>"]
edition = "2018"

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.2"
log = "0.4"
simplelog = { version = "0.9", default-features = false }
better-panic = "0.2"

libwifi = { path = "../../libraries/libwifi" }

pcap = { version = "0.8", features = ['capture-stream'] }
radiotap = "1.3"
